export * from './Register'
export * from './CheckCode'
export * from './Dashboard'
export * from './ForgotPassword'
export * from './Home'
export * from './Login'
export * from './NotFound'
export * from './Profile'
